package com.example.firedatabase_assis.login_setup

data class Language(val iso_639_1: String, val englishName: String, val nativeName: String)

// Create a list of Language instances
val languages = listOf(
    Language("bi", "Bislama", ""),
    Language("cs", "Czech", "Český"),
    Language("ba", "Bashkir", ""),
    Language("ae", "Avestan", ""),
    Language("av", "Avaric", ""),
    Language("de", "German", "Deutsch"),
    Language("mt", "Maltese", "Malti"),
    Language("om", "Oromo", ""),
    Language("rm", "Raeto-Romance", ""),
    Language("so", "Somali", "Somali"),
    Language("ts", "Tsonga", ""),
    Language("vi", "Vietnamese", "Tiếng Việt"),
    Language("gn", "Guarani", ""),
    Language("ig", "Igbo", ""),
    Language("it", "Italian", "Italiano"),
    Language("ki", "Kikuyu", ""),
    Language("ku", "Kurdish", ""),
    Language("la", "Latin", "Latin"),
    Language("ln", "Lingala", ""),
    Language("lb", "Letzeburgesch", ""),
    Language("ny", "Chichewa; Nyanja", ""),
    Language("pl", "Polish", "Polski"),
    Language("si", "Sinhalese", "සිංහල"),
    Language("to", "Tonga", ""),
    Language("az", "Azerbaijani", "Azərbaycan"),
    Language("ce", "Chechen", ""),
    Language("cu", "Slavic", ""),
    Language("da", "Danish", "Dansk"),
    Language("hz", "Herero", ""),
    Language("ie", "Interlingue", ""),
    Language("rw", "Kinyarwanda", "Kinyarwanda"),
    Language("mi", "Maori", ""),
    Language("no", "Norwegian", "Norsk"),
    Language("pi", "Pali", ""),
    Language("sk", "Slovak", "Slovenčina"),
    Language("se", "Northern Sami", ""),
    Language("sm", "Samoan", ""),
    Language("uk", "Ukrainian", "Український"),
    Language("en", "English", "English"),
    Language("ay", "Aymara", ""),
    Language("ca", "Catalan", "Català"),
    Language("eo", "Esperanto", "Esperanto"),
    Language("ha", "Hausa", "Hausa"),
    Language("ho", "Hiri Motu", ""),
    Language("hu", "Hungarian", "Magyar"),
    Language("io", "Ido", ""),
    Language("ii", "Yi", ""),
    Language("kn", "Kannada", "?????"),
    Language("kv", "Komi", ""),
    Language("li", "Limburgish", ""),
    Language("oj", "Ojibwa", ""),
    Language("ru", "Russian", "Pусский"),
    Language("sr", "Serbian", "Srpski"),
    Language("sv", "Swedish", "svenska"),
    Language("ty", "Tahitian", ""),
    Language("zu", "Zulu", "isiZulu"),
    Language("ka", "Georgian", "ქართული"),
    Language("ch", "Chamorro", "Finu' Chamorro"),
    Language("be", "Belarusian", "беларуская мова"),
    Language("br", "Breton", ""),
    Language("kw", "Cornish", ""),
    Language("fi", "Finnish", "suomi"),
    Language("sh", "Serbo-Croatian", ""),
    Language("nn", "Norwegian Nynorsk", ""),
    Language("tt", "Tatar", ""),
    Language("tg", "Tajik", ""),
    Language("vo", "Volapük", ""),
    Language("ps", "Pushto", "پښتو"),
    Language("mk", "Macedonian", ""),
    Language("fr", "French", "Français"),
    Language("bm", "Bambara", "Bamanankan"),
    Language("eu", "Basque", "euskera"),
    Language("fj", "Fijian", ""),
    Language("id", "Indonesian", "Bahasa indonesia"),
    Language("mg", "Malagasy", ""),
    Language("na", "Nauru", ""),
    Language("xx", "No Language", "No Language"),
    Language("qu", "Quechua", ""),
    Language("sq", "Albanian", "shqip"),
    Language("ti", "Tigrinya", ""),
    Language("tw", "Twi", ""),
    Language("wa", "Walloon", ""),
    Language("ab", "Abkhazian", ""),
    Language("bs", "Bosnian", "Bosanski"),
    Language("af", "Afrikaans", "Afrikaans"),
    Language("an", "Aragonese", ""),
    Language("fy", "Frisian", ""),
    Language("gu", "Gujarati", ""),
    Language("ik", "Inupiaq", ""),
    Language("ja", "Japanese", "日本語"),
    Language("ko", "Korean", "한국어/조선말"),
    Language("lg", "Ganda", ""),
    Language("nl", "Dutch", "Nederlands"),
    Language("os", "Ossetian; Ossetic", ""),
    Language("el", "Greek", "ελληνικά"),
    Language("bn", "Bengali", "বাংলা"),
    Language("cr", "Cree", ""),
    Language("km", "Khmer", ""),
    Language("lo", "Lao", ""),
    Language("nd", "Ndebele", ""),
    Language("ne", "Nepali", ""),
    Language("sc", "Sardinian", ""),
    Language("sw", "Swahili", "Kiswahili"),
    Language("tl", "Tagalog", ""),
    Language("ur", "Urdu", "اردو"),
    Language("ee", "Ewe", "Èʋegbe"),
    Language("aa", "Afar", ""),
    Language("co", "Corsican", ""),
    Language("et", "Estonian", "Eesti"),
    Language("is", "Icelandic", "Íslenska"),
    Language("ks", "Kashmiri", ""),
    Language("kr", "Kanuri", ""),
    Language("ky", "Kirghiz", "??????"),
    Language("kj", "Kuanyama", ""),
    Language("nr", "Ndebele", ""),
    Language("or", "Oriya", ""),
    Language("wo", "Wolof", "Wolof"),
    Language("za", "Zhuang", ""),
    Language("ar", "Arabic", "العربية"),
    Language("cv", "Chuvash", ""),
    Language("fo", "Faroese", ""),
    Language("hr", "Croatian", "Hrvatski"),
    Language("ms", "Malay", "Bahasa melayu"),
    Language("nb", "Norwegian Bokmål", "Bokmål"),
    Language("rn", "Rundi", "Kirundi"),
    Language("sn", "Shona", ""),
    Language("st", "Sotho", ""),
    Language("tr", "Turkish", "Türkçe"),
    Language("am", "Amharic", ""),
    Language("fa", "Persian", "فارسی"),
    Language("hy", "Armenian", ""),
    Language("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    Language("as", "Assamese", ""),
    Language("ia", "Interlingua", ""),
    Language("lv", "Latvian", "Latviešu"),
    Language("lu", "Luba-Katanga", ""),
    Language("mr", "Marathi", ""),
    Language("mn", "Mongolian", ""),
    Language("pt", "Portuguese", "Português"),
    Language("th", "Thai", "ภาษาไทย"),
    Language("tk", "Turkmen", ""),
    Language("ve", "Venda", ""),
    Language("dv", "Divehi", ""),
    Language("gv", "Manx", ""),
    Language("kl", "Kalaallisut", ""),
    Language("kk", "Kazakh", "қазақ"),
    Language("lt", "Lithuanian", "Lietuvių"),
    Language("my", "Burmese", ""),
    Language("sl", "Slovenian", "Slovenščina"),
    Language("sd", "Sindhi", ""),
    Language("cn", "Cantonese", "广州话 / 廣州話"),
    Language("hi", "Hindi", "हिन्दी"),
    Language("cy", "Welsh", "Cymraeg"),
    Language("ht", "Haitian; Haitian Creole", ""),
    Language("iu", "Inuktitut", ""),
    Language("jv", "Javanese", ""),
    Language("mh", "Marshall", ""),
    Language("sa", "Sanskrit", ""),
    Language("ss", "Swati", ""),
    Language("te", "Telugu", "తెలుగు"),
    Language("kg", "Kongo", ""),
    Language("ml", "Malayalam", ""),
    Language("uz", "Uzbek", "ozbek"),
    Language("sg", "Sango", ""),
    Language("xh", "Xhosa", ""),
    Language("es", "Spanish", "Español"),
    Language("bg", "Bulgarian", "български език"),
    Language("bo", "Tibetan", ""),
    Language("kl", "Kalaallisut", "ᐃᓄᒃᑎᑐᑦ"),
    Language("ak", "Akan", ""),
    Language("ff", "Fulah", ""),
    Language("gl", "Galician", "Galego"),
    Language("kv", "Komi", "Коми кыв"),
    Language("zh", "Mandarin", "普通话/国语"),
    Language("kn", "Kannada", "ಕನ್ನಡ"),
    Language("eo", "Esperanto", ""),
    Language("is", "Icelandic", ""),
    Language("hy", "Armenian", ""),
    Language("he", "Hebrew", "עִבְרִית"),
    Language("si", "Sinhalese", ""),
    Language("pl", "Polish", ""),
    Language("no", "Norwegian", ""),
    Language("lv", "Latvian", ""),
    Language("en", "English", ""),
    Language("pa", "Punjabi", ""),
    Language("kk", "Kazakh", ""),
    Language("ko", "Korean", ""),
    Language("ta", "Tamil", ""),
    Language("my", "Burmese", ""),
    Language("jv", "Javanese", ""),
    Language("de", "German", ""),
    Language("el", "Greek", ""),
    Language("af", "Afrikaans", ""),
    Language("sr", "Serbian", ""),
    Language("hu", "Hungarian", ""),
    Language("vi", "Vietnamese", ""),
    Language("or", "Oriya", ""),
    Language("bg", "Bulgarian", ""),
    Language("es", "Spanish", ""),
    Language("ru", "Russian", ""),
    Language("mk", "Macedonian", ""),
    Language("hr", "Croatian", ""),
    Language("da", "Danish", ""),
    Language("ne", "Nepali", ""),
    Language("ta", "Tamil", ""),
    Language("th", "Thai", ""),
    Language("km", "Khmer", ""),
    Language("pt", "Portuguese", ""),
    Language("sv", "Swedish", ""),
    Language("bn", "Bengali", ""),
    Language("te", "Telugu", ""),
    Language("ml", "Malayalam", ""),
    Language("hi", "Hindi", ""),
    Language("fa", "Persian", ""),
    Language("id", "Indonesian", ""),
    Language("he", "Hebrew", ""),
    Language("ar", "Arabic", ""),
    Language("th", "Thai", ""),
    Language("ja", "Japanese", ""),
    Language("fr", "French", ""),
    Language("tr", "Turkish", ""),
    Language("it", "Italian", ""),
    Language("zh", "Mandarin", ""),
    Language("ur", "Urdu", ""),
    Language("ko", "Korean", ""),
    Language("pa", "Punjabi", ""),
    Language("xx", "No Language", ""),
    Language("xx", "No Language", ""),
    Language("aa", "Afar", ""),
    Language("ab", "Abkhazian", ""),
    Language("ae", "Avestan", ""),
    Language("af", "Afrikaans", ""),
    Language("ak", "Akan", ""),
    Language("am", "Amharic", ""),
    Language("an", "Aragonese", ""),
    Language("ar", "Arabic", ""),
    Language("as", "Assamese", ""),
    Language("av", "Avaric", ""),
    Language("ay", "Aymara", ""),
    Language("az", "Azerbaijani", ""),
    Language("ba", "Bashkir", ""),
    Language("be", "Belarusian", ""),
    Language("bg", "Bulgarian", ""),
    Language("bh", "Bihari", ""),
    Language("bi", "Bislama", ""),
    Language("bm", "Bambara", ""),
    Language("bn", "Bengali", ""),
    Language("bo", "Tibetan", ""),
    Language("br", "Breton", ""),
    Language("bs", "Bosnian", ""),
    Language("ca", "Catalan", ""),
    Language("ce", "Chechen", ""),
    Language("ch", "Chamorro", ""),
    Language("co", "Corsican", ""),
    Language("cr", "Cree", ""),
    Language("cs", "Czech", ""),
    Language("cu", "Slavic", ""),
    Language("cv", "Chuvash", ""),
    Language("cy", "Welsh", ""),
    Language("da", "Danish", ""),
    Language("de", "German", ""),
    Language("dv", "Divehi", ""),
    Language("dz", "Dzongkha", ""),
    Language("ee", "Ewe", ""),
    Language("el", "Greek", ""),
    Language("en", "English", ""),
    Language("eo", "Esperanto", ""),
    Language("es", "Spanish", ""),
    Language("et", "Estonian", ""),
    Language("eu", "Basque", ""),
    Language("fa", "Persian", ""),
    Language("ff", "Fulah", ""),
    Language("fi", "Finnish", ""),
    Language("fj", "Fijian", ""),
    Language("fo", "Faroese", ""),
    Language("fr", "French", ""),
    Language("fy", "Frisian", ""),
    Language("ga", "Irish", ""),
    Language("gd", "Gaelic", ""),
    Language("gl", "Galician", ""),
    Language("gn", "Guarani", ""),
    Language("gu", "Gujarati", ""),
    Language("gv", "Manx", ""),
    Language("ha", "Hausa", ""),
    Language("he", "Hebrew", ""),
    Language("hi", "Hindi", ""),
    Language("ho", "Hiri Motu", ""),
    Language("hr", "Croatian", ""),
    Language("ht", "Haitian; Haitian Creole", ""),
    Language("hu", "Hungarian", ""),
    Language("hy", "Armenian", ""),
    Language("hz", "Herero", ""),
    Language("ia", "Interlingua", ""),
    Language("id", "Indonesian", ""),
    Language("ie", "Interlingue", ""),
    Language("ig", "Igbo", ""),
    Language("ii", "Yi", ""),
    Language("ik", "Inupiaq", ""),
    Language("io", "Ido", ""),
    Language("is", "Icelandic", ""),
    Language("it", "Italian", ""),
    Language("iu", "Inuktitut", ""),
    Language("ja", "Japanese", ""),
    Language("jv", "Javanese", ""),
    Language("ka", "Georgian", ""),
    Language("kg", "Kongo", ""),
    Language("ki", "Kikuyu", ""),
    Language("kj", "Kuanyama", ""),
    Language("kk", "Kazakh", ""),
    Language("kl", "Kalaallisut", ""),
    Language("km", "Khmer", ""),
    Language("kn", "Kannada", ""),
    Language("ko", "Korean", ""),
    Language("kr", "Kanuri", ""),
    Language("ks", "Kashmiri", ""),
    Language("ku", "Kurdish", ""),
    Language("kv", "Komi", ""),
    Language("kw", "Cornish", ""),
    Language("ky", "Kirghiz", ""),
    Language("la", "Latin", ""),
    Language("lb", "Letzeburgesch", ""),
    Language("lg", "Ganda", ""),
    Language("li", "Limburgish", ""),
    Language("ln", "Lingala", ""),
    Language("lo", "Lao", ""),
    Language("lt", "Lithuanian", ""),
    Language("lu", "Luba-Katanga", ""),
    Language("lv", "Latvian", ""),
    Language("mg", "Malagasy", ""),
    Language("mh", "Marshall", ""),
    Language("mi", "Maori", ""),
    Language("mk", "Macedonian", ""),
    Language("ml", "Malayalam", ""),
    Language("mn", "Mongolian", ""),
    Language("mr", "Marathi", ""),
    Language("ms", "Malay", ""),
    Language("mt", "Maltese", ""),
    Language("my", "Burmese", ""),
    Language("na", "Nauru", ""),
    Language("nb", "Norwegian Bokmål", ""),
    Language("nd", "Ndebele", ""),
    Language("ne", "Nepali", ""),
    Language("ng", "Ndonga", ""),
    Language("nl", "Dutch", ""),
    Language("nn", "Norwegian Nynorsk", ""),
    Language("no", "Norwegian", ""),
    Language("nr", "Ndebele", ""),
    Language("nv", "Navajo", ""),
    Language("ny", "Chichewa; Nyanja", ""),
    Language("oc", "Occitan", ""),
    Language("oj", "Ojibwa", ""),
    Language("om", "Oromo", ""),
    Language("or", "Oriya", ""),
    Language("os", "Ossetian; Ossetic", ""),
    Language("pa", "Punjabi", ""),
    Language("pi", "Pali", ""),
    Language("pl", "Polish", ""),
    Language("ps", "Pushto", ""),
    Language("pt", "Portuguese", ""),
    Language("qu", "Quechua", ""),
    Language("rm", "Romansh", ""),
    Language("rn", "Rundi", ""),
    Language("ro", "Romanian", ""),
    Language("ru", "Russian", ""),
    Language("rw", "Kinyarwanda", ""),
    Language("sa", "Sanskrit", ""),
    Language("sc", "Sardinian", ""),
    Language("sd", "Sindhi", ""),
    Language("se", "Northern Sami", ""),
    Language("sg", "Sango", ""),
    Language("si", "Sinhalese", ""),
    Language("sk", "Slovak", ""),
    Language("sl", "Slovenian", ""),
    Language("sm", "Samoan", ""),
    Language("sn", "Shona", ""),
    Language("so", "Somali", ""),
    Language("sq", "Albanian", ""),
    Language("sr", "Serbian", ""),
    Language("ss", "Swati", ""),
    Language("st", "Sotho", ""),
    Language("su", "Sundanese", ""),
    Language("sv", "Swedish", ""),
    Language("sw", "Swahili", ""),
    Language("ta", "Tamil", ""),
    Language("te", "Telugu", ""),
    Language("tg", "Tajik", ""),
    Language("th", "Thai", ""),
    Language("ti", "Tigrinya", ""),
    Language("tk", "Turkmen", ""),
    Language("tl", "Tagalog", ""),
    Language("tn", "Tswana", ""),
    Language("to", "Tonga", ""),
    Language("tr", "Turkish", ""),
    Language("ts", "Tsonga", ""),
    Language("tt", "Tatar", ""),
    Language("tw", "Twi", ""),
    Language("ty", "Tahitian", ""),
    Language("ug", "Uighur", ""),
    Language("uk", "Ukrainian", ""),
    Language("ur", "Urdu", ""),
    Language("uz", "Uzbek", ""),
    Language("ve", "Venda", ""),
    Language("vi", "Vietnamese", ""),
    Language("vo", "Volapük", ""),
    Language("wa", "Walloon", ""),
    Language("wo", "Wolof", ""),
    Language("xh", "Xhosa", ""),
    Language("yi", "Yiddish", ""),
    Language("yo", "Yoruba", ""),
    Language("za", "Zhuang", ""),
    Language("zh", "Mandarin", ""),
    Language("zu", "Zulu", "")
)

// Create a map that links English names to ISO 639-1 codes
val languageMap = languages.associateBy({ it.englishName.lowercase() }, { it.iso_639_1 })

// Function to get ISO 639-1 code from English name
fun getIso6391(englishName: String): String {
    return languageMap[englishName.lowercase()] ?: "Language not found"
}

data class Provider(val provider_name: String, val provider_id: Int)


data class Genre(val name: String, var isChecked: Boolean = false)